import { Table } from "@mantine/core";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { FooterLinks } from "../components/Footer";
import { HeaderTabs } from "../components/HeaderTabs";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Chainized</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderTabs
        user={{
          name: "keinsell",
          image: "https://avatars.githubusercontent.com/u/41811819?v=4",
        }}
        tabs={["test"]}
      ></HeaderTabs>
      <div className={styles.container}>
        <h6>TODO: Integration with wallet</h6>
        <h6>TODO: Read data from contract</h6>
        <h6>TODO: Interact with contract</h6>
        <h6>TODO: Optional interact with contract with api</h6>
      </div>
      <FooterLinks
        data={[{ title: "test", links: [{ label: "test", link: "test" }] }]}
      ></FooterLinks>
    </>
  );
};

export default Home;
