version: "3"
services:
  ethereum:
    container_name: chainized-ethereum
    image: trufflesuite/ganache-cli:latest
    ports:
      - 8545:8545
  solana:
    image: solanalabs/solana:stable
    container_name: chainized-solana
    ports:
      - 8899:8899
      - 8900:8900