[features]
seeds = false

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "./../../packages/config/solana/id.json"

[scripts]
test = "pnpm npx ava --timeout=10m"