[features]
seeds = false
skip-lint = false

[programs.localnet]
coinflip_bet = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./../config/solana/id.json"

[scripts]
test = "pnpm npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
